### ISSUE TITLE
regex compilation error is not very descriptive

### ISSUE THREAD

**Issue by rexim** [tsoding/cm#68]
introduced in #66
